"""Parse Excel mapping templates and build StructureMaps from them."""

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Literal

import pandas as pd
from pysdmx.model.map import (
    ComponentMap,
    FixedValueMap,
    ImplicitComponentMap,
    MultiComponentMap,
    StructureMap,
)
from typeguard import typechecked

from ..tidysdmx import parse_artefact_id
from .map_builders import (
    build_fixed_map,
    build_implicit_component_map,
    build_multi_component_map,
    build_single_component_map,
)
from .urn import gen_urn


@typechecked
def _parse_info_sheet(
    sheets: dict[str, pd.DataFrame], sheet_name: str = "INFO"
) -> pd.DataFrame:
    """Parse the INFO sheet into key-value metadata.

    Extracts a specific DataFrame from the provided dictionary. Handles arbitrary
    layouts by treating headers as potential data, unless the headers appear to be
    auto-generated (RangeIndex). Keeps key-value rows containing one or two
    non-empty values (the value may be empty).

    Args:
        sheets: Dictionary containing DataFrames, typically from pd.read_excel.
        sheet_name: Name of the sheet to parse. Defaults to "INFO".

    Returns:
        A DataFrame with columns ['Key', 'Value'] containing the extracted metadata.

    Raises:
        ValueError: If the specified sheet_name is not found in the dictionary.
    """
    if sheet_name not in sheets:
        raise ValueError(f"Sheet '{sheet_name}' not found in the provided dictionary.")

    df = sheets[sheet_name]

    # Normalize data extraction:
    # 1. If columns are a RangeIndex (0, 1, 2...), they are likely
    #    auto-generated by pandas (e.g. pd.DataFrame() without columns) and
    #    should be ignored.
    # 2. Otherwise, we treat columns as the first row of data, which covers
    #    cases where pd.read_excel(header=0) consumes the first row of actual
    #    metadata as the header.
    if isinstance(df.columns, pd.RangeIndex):
        all_rows = df.values.tolist()
    else:
        all_rows = [df.columns.tolist(), *df.values.tolist()]

    cleaned_rows: list[list[str]] = []

    for row in all_rows:
        valid_cells = []
        for cell in row:
            # Basic validation: check for NaN/None
            if pd.isna(cell):
                continue

            s_cell = str(cell).strip()

            # Check for empty strings, 'nan' string literals, and pandas
            # 'Unnamed' artifacts
            if s_cell == "" or s_cell.lower() == "nan" or s_cell.startswith("Unnamed:"):
                continue

            valid_cells.append(s_cell)

        if not valid_cells:
            continue

        # Ignore the specific header row mentioned in requirements
        if any("DATA CURATION PROCESS" in cell for cell in valid_cells):
            continue

        # We strictly look for Key-Value pairs (but allow the second item to be empty)
        if len(valid_cells) <= 2:
            cleaned_rows.append(valid_cells)

    if not cleaned_rows:
        return pd.DataFrame(columns=["Key", "Value"])

    return pd.DataFrame(cleaned_rows, columns=["Key", "Value"])


@typechecked
def _parse_comp_mapping_sheet(
    sheets: dict[str, pd.DataFrame], sheet_name: str = "COMP_MAPPING"
) -> pd.DataFrame:
    """Parse the COMP_MAPPING sheet, validating strict structure conformance.

    Expects the sheet to contain specific headers: 'SOURCE', 'TARGET',
    and 'MAPPING_RULES'. Extracts these columns, removes completely empty rows,
    and returns the resulting DataFrame. Rows with partial data (e.g., missing
    'SOURCE') are preserved as they are valid mapping rules.

    Args:
        sheets: Dictionary containing DataFrames, typically from pd.read_excel.
        sheet_name: Name of the sheet to parse. Defaults to "COMP_MAPPING".

    Returns:
        A DataFrame containing 'SOURCE', 'TARGET', and 'MAPPING_RULES' columns.

    Raises:
        ValueError: If the sheet is missing or does not contain the required columns.
    """
    if sheet_name not in sheets:
        raise ValueError(f"Sheet '{sheet_name}' not found in the provided dictionary.")

    df = sheets[sheet_name]

    required_columns = ["SOURCE", "TARGET", "MAPPING_RULES"]
    optional_columns = ["SOURCE_CL", "TARGET_CL", "DEFAULT_VALUE"]

    # Validate that required columns exist
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        raise ValueError(
            f"Sheet '{sheet_name}' is missing required columns: {missing_columns}. "
            f"Found: {df.columns.tolist()}"
        )

    # Extract required columns + any optional columns that exist
    cols_to_extract = required_columns + [
        c for c in optional_columns if c in df.columns
    ]
    result_df = df[cols_to_extract].copy()

    # Ensure optional columns exist in output (fill with None if absent from sheet)
    for col in optional_columns:
        if col not in result_df.columns:
            result_df[col] = None

    # Remove rows where ALL columns are NaN/None (empty rows)
    # We do not use how='any' because some mapping rules might have an empty SOURCE
    result_df.dropna(how="all", inplace=True)

    return result_df


@typechecked
def _parse_rep_mapping_sheet(
    sheets: dict[str, pd.DataFrame], sheet_name: str = "REP_MAPPING"
) -> dict[str, pd.DataFrame]:
    """Parses the REP_MAPPING sheet to split columns into Source and Target DataFrames.

    The function expects column headers to be prefixed with "S:" for source columns and
    "T:" for target columns. Columns without these prefixes are ignored. The prefixes
    are removed in the output DataFrames.

    Args:
        sheets (dict[str, pd.DataFrame]): Dictionary containing DataFrames.
        sheet_name (str): Name of the sheet to parse. Defaults to "REP_MAPPING".

    Returns:
        dict[str, pd.DataFrame]: A dict with keys ``"source"`` and ``"target"``,
            each containing a DataFrame with the prefix stripped from column names.

    Raises:
        ValueError: If the sheet is missing, or if no Source/Target columns are found.
    """
    if sheet_name not in sheets:
        raise ValueError(f"Sheet '{sheet_name}' not found in the provided dictionary.")

    df = sheets[sheet_name]

    # Identify columns based on prefixes
    source_cols = [col for col in df.columns if str(col).startswith("S:")]
    target_cols = [col for col in df.columns if str(col).startswith("T:")]

    if not source_cols:
        raise ValueError(
            f"No source columns (prefixed with 'S:') found in '{sheet_name}'."
        )

    if not target_cols:
        raise ValueError(
            f"No target columns (prefixed with 'T:') found in '{sheet_name}'."
        )

    # Create distinct DataFrames
    source_df = df[source_cols]
    target_df = df[target_cols]

    # Rename columns by removing the first 2 characters ("S:" and "T:")
    source_df.columns = [col[2:] for col in source_cols]
    target_df.columns = [col[2:] for col in target_cols]

    return {"source": source_df, "target": target_df}


@typechecked
def _match_column_name(target_name: str, available_columns: list[str]) -> str:
    """Match a business name from COMP_MAPPING to cleaned column names in REP_MAPPING.

    Handles discrepancies like 'Series code' (business name) vs 'Series'
    (Excel header).

    Args:
        target_name: The name to look for (e.g., 'Series code').
        available_columns: The list of available column headers.

    Returns:
        The matching column name.

    Raises:
        ValueError: If no suitable match is found.
    """
    # 1. Exact match
    if target_name in available_columns:
        return target_name

    # 2. Normalized match (ignore case, spaces, underscores)
    norm_target = target_name.replace(" ", "").replace("_", "").lower()
    norm_cols = [
        (col, col.replace(" ", "").replace("_", "").lower())
        for col in available_columns
    ]

    # 2a. Normalized equality takes priority and must be unambiguous.
    equal = [col for col, norm in norm_cols if norm == norm_target]
    if len(equal) == 1:
        return equal[0]
    if len(equal) > 1:
        raise ValueError(
            f"Ambiguous match for '{target_name}': columns {equal} all normalize "
            f"identically. Rename the REP_MAPPING header to match the component id."
        )

    # 2b. Fall back to substring containment, but only when the candidate is
    # unique — otherwise a header like 'AGE' would silently bind to 'PERCENTAGE'.
    contained = [
        col for col, norm in norm_cols if norm in norm_target or norm_target in norm
    ]
    if len(contained) == 1:
        return contained[0]
    if len(contained) > 1:
        raise ValueError(
            f"Ambiguous match for '{target_name}': multiple candidate columns "
            f"{contained}. Rename the REP_MAPPING header to match the component "
            f"id exactly."
        )

    raise ValueError(
        f"Could not find a column in REP_MAPPING matching '{target_name}'. "
        f"Available: {available_columns}"
    )


@typechecked
def _collect_required_sheet_errors(
    mappings: dict[str, pd.DataFrame],
    required_keys: Iterable[str],
) -> list[str]:
    """Collect validation errors related to missing required sheets."""
    errors: list[str] = []

    # Check that mandatory sheets are present
    for sheet_name in required_keys:
        if sheet_name not in mappings:
            msg = f"Missing required sheet: '{sheet_name}'."
            errors.append(msg)

    return errors


@typechecked
def _collect_mapping_rules_errors(
    comp_mapping: pd.DataFrame,
    *,  # Ensures following args are keyword-only
    valid_rules: Iterable[str],
    valid_prefixes: Iterable[str],
) -> list[str]:
    """Collect validation errors for the MAPPING_RULES column in COMP_MAPPING.

    Rules:
        * Column 'MAPPING_RULES' must exist.
        * Each non-null entry must be:
            - one of valid_rules
            - or start with one of valid_prefixes followed by a non-empty value.
    """
    errors: list[str] = []

    if "MAPPING_RULES" not in comp_mapping.columns:
        msg = "COMP_MAPPING sheet is missing required 'MAPPING_RULES' column."

        errors.append(msg)
        return errors

    valid_set = set(valid_rules)

    # Normalize prefixes once
    prefixes = tuple(str(p) for p in valid_prefixes)
    if not prefixes or any(p == "" for p in prefixes):
        raise ValueError("Argument 'valid_prefixes' must contain non-empty strings.")

    rules_series = comp_mapping["MAPPING_RULES"]

    for row_idx, raw_value in rules_series.items():
        if pd.isna(raw_value):
            continue

        value = str(raw_value).strip()

        # 1) Literal rules
        if value in valid_set:
            continue

        # 2) Prefixed rules (enforce non-empty parsed_value)
        matched_prefix = next((p for p in prefixes if value.startswith(p)), None)
        if matched_prefix is not None:
            parsed_value = value[len(matched_prefix) :].strip()
            if not parsed_value:
                msg = (
                    f"Invalid MAPPING_RULES value at row {row_idx}: '{raw_value}'. "
                    f"Rule '{matched_prefix}' must be followed by a non-empty value, "
                    f"e.g. '{matched_prefix}A'."
                )

                errors.append(msg)
            # either way, we handled a recognized prefix (valid or invalid)
            continue

        # 3) Everything else invalid
        msg = (
            f"Invalid MAPPING_RULES value at row {row_idx}: '{raw_value}'. "
            "Expected one of "
            f"{sorted(valid_set)!r} "
            f"or a string starting with one of {list(prefixes)!r}."
        )

        errors.append(msg)

    return errors


@typechecked
def _validate_mapping_template_wb(
    mappings: dict[str, pd.DataFrame],
    *,  # Ensures following args are keyword-only
    required_keys: Iterable[str] = ("INFO", "COMP_MAPPING", "REP_MAPPING"),
    valid_rules: Iterable[str] = ("representation", "multi_representation", "implicit"),
    valid_prefixes: Iterable[str] = ("fixed:",),
) -> None:
    """Validate a mapping template workbook represented as a mapping of DataFrames.

    If any validation fails, raises ValueError listing all issues.
    """
    # Ensure functions arguments are of the expected type
    for key in mappings:
        # All keys should be strings
        if not isinstance(key, str):
            raise ValueError(
                f"All keys must be strings. Key: '{key}' is of type "
                f"{type(key).__name__}."
            )
        # Values should be dataframes
        if not isinstance(mappings[key], pd.DataFrame):
            raise ValueError(
                f"Sheet '{key}' must be a pandas DataFrame, "
                f"got {type(mappings[key]).__name__}."
            )

    errors: list[str] = []

    # 1) Check required sheet presence and type validity
    errors.extend(_collect_required_sheet_errors(mappings, required_keys))

    # 2) Validate mapping_rules
    comp_mapping = mappings.get("COMP_MAPPING")
    if comp_mapping is not None:
        errors.extend(
            _collect_mapping_rules_errors(
                comp_mapping,
                valid_rules=valid_rules,
                valid_prefixes=valid_prefixes,
            )
        )

    if errors:
        full_message = (
            "Mapping template workbook validation failed with the "
            "following issues:\n- " + "\n- ".join(errors)
        )
        raise ValueError(full_message)


STRUCTURE_TYPE_TO_ARTEFACT: dict[str, str] = {
    "datastructure": "DataStructure",
    "dataflow": "Dataflow",
    "provisionagreement": "ProvisionAgreement",
}


@typechecked
def build_structure_map_from_template_wb(
    mappings: dict[str, pd.DataFrame],
    agency: str = "SDMX",
    structure_map_id: str = "WB_STRUCTURE_MAP",
    structure_type: Literal[
        "datastructure", "dataflow", "provisionagreement"
    ] = "datastructure",
    version: str = "1.0",
    required_keys: Iterable[str] = ("INFO", "COMP_MAPPING", "REP_MAPPING"),
    valid_rules: Iterable[str] = ("representation", "multi_representation", "implicit"),
    valid_prefixes: Iterable[str] = ("fixed:",),
    generate_urns: bool = True,
    source_structure_id: str | None = None,
    target_structure_id: str | None = None,
) -> StructureMap:
    """Build a complete StructureMap object by parsing a WB-format Excel template.

    Args:
        mappings: Dictionary of DataFrames containing all sheets.
        agency: Fallback agency ID if not found in INFO.
        structure_map_id: ID for the resulting StructureMap.
        structure_type: The type of artefact to extract from INFO.
        version: Fallback version if not found in INFO.
        required_keys: Required sheet names to validate.
        valid_rules: Valid literal mapping rules.
        valid_prefixes: Valid prefixes for parameterized mapping rules.
        generate_urns: If True, automatically generate URNs for StructureMap
            and nested RepresentationMaps. Defaults to True.
        source_structure_id: Optional source structure reference in
            ``"AGENCY:ID(VERSION)"`` format (e.g. ``"WB:DSD_ASPIRE(1.0)"``).
            When provided and ``generate_urns`` is True, a full SDMX URN is
            built and set as the StructureMap's ``source``.
        target_structure_id: Optional target structure reference in
            ``"AGENCY:ID(VERSION)"`` format (e.g. ``"WB:DSD_WDI(1.0)"``).
            When provided and ``generate_urns`` is True, a full SDMX URN is
            built and set as the StructureMap's ``target``.

    Returns:
        A valid pysdmx StructureMap object.

    Raises:
        ValueError: If mandatory sheets/columns are missing or mapping rules
            are invalid.

    Examples:
        >>> mappings = {
        ...     "INFO": pd.DataFrame(
        ...         {"Key": ["datastructure"], "Value": ["TEST_AGENCY:DSD_ID(1.0)"]}
        ...     ),
        ...     "COMP_MAPPING": pd.DataFrame(
        ...         {
        ...             "SOURCE": ["src"],
        ...             "TARGET": ["tgt"],
        ...             "MAPPING_RULES": ["fixed:VAL"],
        ...         }
        ...     ),
        ...     "REP_MAPPING": pd.DataFrame({"S:src": ["a"], "T:tgt": ["b"]})
        ... }
        >>> smap = build_structure_map_from_template_wb(mappings)
        >>> smap.agency
        'TEST_AGENCY'
        >>> isinstance(smap, StructureMap)
        True
    """
    # Validate mappings upfront
    _validate_mapping_template_wb(
        mappings,
        required_keys=required_keys,
        valid_rules=valid_rules,
        valid_prefixes=valid_prefixes,
    )

    # 1. Extract Metadata (Agency & Version)
    info_df = _parse_info_sheet(mappings)
    current_agency, current_version, artefact_ref = _extract_metadata_from_info_sheet(
        info_df=info_df, agency=agency, version=version, structure_type=structure_type
    )

    # 2. Parse Component Mappings Rules
    comp_df = _parse_comp_mapping_sheet(mappings)

    # 3. Prepare Representation Data
    # Defer invalid-REP_MAPPING failures: a template may not reference it at
    # all. Stash the parse error so it can be surfaced if a rule *does* need it.
    rep_data: dict[str, pd.DataFrame] = {}
    rep_data_error: str | None = None
    try:
        rep_data = _parse_rep_mapping_sheet(mappings)
    except ValueError as exc:
        rep_data_error = str(exc)

    generated_maps: list[
        FixedValueMap | ImplicitComponentMap | ComponentMap | MultiComponentMap
    ] = []

    # Track RepresentationMap IDs to avoid duplicates
    rep_map_counter = {}

    # 4. Generate structure map elements
    for _, row in comp_df.iterrows():
        try:
            parsed = _extract_mapping_rule(row)
            mapping_rule = parsed.mapping_rule
            source_id = parsed.source_id or ""  # normalize to str
            target_id = parsed.target_id or ""  # normalize to str

            if mapping_rule == "skip":
                continue

            if mapping_rule == "fixed":
                fixed_val = parsed.fixed_value  # guaranteed non-empty by parser
                generated_maps.append(build_fixed_map(target_id, fixed_val))  # type: ignore[arg-type]

            elif mapping_rule == "implicit":
                generated_maps.append(
                    build_implicit_component_map(source_id, target_id)
                )

            elif mapping_rule == "representation":
                rep_mapping_df = _extract_representation_map(
                    rep_data=rep_data,
                    source_id=source_id,
                    target_id=target_id,
                    rep_data_error=rep_data_error,
                )

                rep_map_id = _unique_map_id(
                    rep_map_counter, f"RM_{source_id}_{target_id}"
                )

                comp_map = build_single_component_map(
                    df=rep_mapping_df,
                    source_component=source_id,
                    target_component=target_id,
                    agency=current_agency,
                    id=rep_map_id,  # Use unique ID
                    name=f"Mapping {source_id} to {target_id}",
                    source_cl=parsed.source_cl,
                    target_cl=parsed.target_cl,
                    source_col="source",
                    target_col="target",
                    version=current_version,
                    generate_urn=generate_urns,  # Pass flag through
                    default_value=parsed.default_value,
                )
                generated_maps.append(comp_map)

            elif mapping_rule == "multi_representation":
                # SOURCE is a '|'-delimited list of >= 2 components
                source_ids = [s.strip() for s in source_id.split("|") if s.strip()]

                multi_df = _extract_multi_representation_map(
                    rep_data=rep_data,
                    source_ids=source_ids,
                    target_id=target_id,
                    rep_data_error=rep_data_error,
                )

                rep_map_id = _unique_map_id(
                    rep_map_counter, f"MRM_{'_'.join(source_ids)}_{target_id}"
                )

                multi_comp_map = build_multi_component_map(
                    df=multi_df,
                    source_components=source_ids,
                    target_components=[target_id],
                    agency=current_agency,
                    id=rep_map_id,  # Use unique ID
                    name=f"Mapping {'|'.join(source_ids)} to {target_id}",
                    target_cls=[parsed.target_cl] if parsed.target_cl else None,
                    version=current_version,
                    generate_urn=generate_urns,  # Pass flag through
                    default_value=parsed.default_value,
                )
                generated_maps.append(multi_comp_map)

            else:
                # Defensive guard
                raise ValueError(f"Unhandled mapping rule: {mapping_rule}")

        except ValueError as e:
            target_for_msg = str(row.get("TARGET", "")).strip()
            raise ValueError(
                f"Error processing mapping for Target '{target_for_msg}': {e!s}"
            ) from e

    # 5. Generate URNs if requested
    structure_map_urn = None
    source_urn = ""
    target_urn = ""
    if generate_urns:
        structure_map_urn = gen_urn(
            "StructureMap", current_agency, structure_map_id, current_version
        )
        artefact_type = STRUCTURE_TYPE_TO_ARTEFACT[structure_type]
        if source_structure_id:
            s_agency, s_id, s_version = parse_artefact_id(source_structure_id)
            source_urn = gen_urn(artefact_type, s_agency, s_id, s_version)
        if target_structure_id:
            t_agency, t_id, t_version = parse_artefact_id(target_structure_id)
            target_urn = gen_urn(artefact_type, t_agency, t_id, t_version)

    # 6. Construct Final Object
    name_suffix = artefact_ref if artefact_ref else structure_map_id
    return StructureMap(
        id=structure_map_id,
        agency=current_agency,
        version=current_version,
        name=f"Structure Map for {name_suffix}",
        urn=structure_map_urn,
        source=source_urn,
        target=target_urn,
        maps=generated_maps,
    )


@typechecked
def _extract_all_artefact_ids(info_df: pd.DataFrame) -> dict[str, str]:
    """Extract artefact IDs from the INFO DataFrame as a structure-type-to-ID mapping.

    Scans the DataFrame for keys corresponding to SDMX artefacts such as
    'dataflow', 'datastructure', and 'provisionagreement', and returns a
    dictionary where each structure type is linked to its raw reference
    string as found in the sheet.

    Args:
        info_df: DataFrame containing metadata with 'Key' and 'Value' columns.

    Returns:
        Dictionary mapping structure types to reference strings
        (e.g. 'AGENCY:DSD1(1.0)').

    Raises:
        ValueError: If the DataFrame is empty, lacks required columns, or no
            artefacts are found.
        TypeError: If info_df is not a pandas DataFrame.

    Examples:
        >>> df = pd.DataFrame({
        ...     'Key': ['dataflow', 'datastructure'],
        ...     'Value': ['AGENCY:DF1(1.0)', 'AGENCY:DSD1(1.0)']
        ... })
        >>> _extract_all_artefact_ids(df)
        {'dataflow': 'AGENCY:DF1(1.0)', 'datastructure': 'AGENCY:DSD1(1.0)'}
    """
    if not isinstance(info_df, pd.DataFrame):
        raise TypeError("info_df must be a pandas DataFrame.")
    if info_df.empty:
        raise ValueError("info_df is empty.")
    if not {"Key", "Value"}.issubset(info_df.columns):
        raise ValueError("info_df must contain 'Key' and 'Value' columns.")

    # Define structure types to look for
    structure_types = {"dataflow", "datastructure", "provisionagreement"}

    # Normalize keys for case-insensitive matching (without mutating input)
    normalized_keys = info_df["Key"].astype(str).str.strip().str.lower()

    # Filter rows matching structure types
    filtered_df = info_df[normalized_keys.isin(structure_types)].copy()
    filtered_df["Key"] = normalized_keys[filtered_df.index]

    if filtered_df.empty:
        raise ValueError("No artefact keys found in info_df.")

    artefact_dict: dict[str, str] = {}
    for _, row in filtered_df.iterrows():
        raw_value = row["Value"]
        if pd.isna(raw_value) or str(raw_value).strip() == "":
            continue
        value_str = str(raw_value).strip()
        artefact_dict[row["Key"]] = value_str

    if not artefact_dict:
        raise ValueError("Artefact keys found but all values are empty or invalid.")

    return artefact_dict


@typechecked
def _extract_metadata_from_info_sheet(
    info_df: pd.DataFrame,
    agency: str,
    version: str,
    structure_type: Literal[
        "datastructure", "dataflow", "provisionagreement"
    ] = "datastructure",
) -> tuple[str, str, str | None]:
    """Extract (agency, version, artefact_ref) from the INFO sheet.

    Uses ``structure_type`` preference, falling back to other artefact
    references when needed. The ``agency``/``version`` arguments are used
    when no reference can be found or parsed.

    Args:
        info_df: INFO sheet with 'Key'/'Value' columns.
        agency: Default agency used when extraction fails.
        version: Default version used when extraction fails.
        structure_type: Preferred structure type. Defaults to
            ``"datastructure"``.

    Returns:
        A tuple of (agency, version, artefact_ref) where artefact_ref
        is the raw reference string or None if not found.
    """
    current_agency = agency
    current_version = version
    artefact_ref: str | None = None

    try:
        artefact_dict: dict[str, str] = _extract_all_artefact_ids(info_df)
    except (ValueError, TypeError, KeyError):
        artefact_dict = {}

    # Preferred artefact by requested structure_type, otherwise fallback order
    if structure_type in artefact_dict:
        artefact_ref = artefact_dict[structure_type]
    else:
        for fallback_type in ("datastructure", "dataflow", "provisionagreement"):
            if fallback_type in artefact_dict:
                artefact_ref = artefact_dict[fallback_type]
                break

    # Parse agency/version from artefact_ref if available
    if artefact_ref:
        try:
            parsed_agency, _, parsed_version = parse_artefact_id(artefact_ref)
            if parsed_agency:
                current_agency = parsed_agency
            if parsed_version:
                current_version = parsed_version
        except (ValueError, TypeError, KeyError):
            # Keep defaults if parsing fails
            pass

    return current_agency, current_version, artefact_ref


_MISSING_RULE_TOKENS = {"nan", "<na>", ""}


@typechecked
def _is_missing_token(s: str) -> bool:
    """Return True if s is a case-insensitive missing token."""
    return s.strip().lower() in _MISSING_RULE_TOKENS


def _cell_str(row: "pd.Series", key: str) -> str:
    """Return a stripped string for *key* in *row*, or ``""`` when missing.

    A cell is missing when it is a pandas NA value (``pd.NA``/``np.nan``/
    ``None``) or when its string form is a missing token (``""``, ``"nan"``,
    ``"<NA>"``). This prevents an empty Excel cell — read as ``pd.NA`` and
    otherwise stringified to the truthy literal ``"<NA>"`` — from being baked
    into a map as a real component ID or value. Legitimate codes such as
    ``"NA"`` (Namibia) are **not** treated as missing.

    Args:
        row: The DataFrame row to read from.
        key: The column label to look up.

    Returns:
        The stripped cell value, or ``""`` if the cell is missing.
    """
    raw = row.get(key)
    if pd.isna(raw):
        return ""
    text = str(raw).strip()
    return "" if _is_missing_token(text) else text


def _unique_map_id(counter: dict[str, int], base: str) -> str:
    """Return a collision-free map ID for *base*, tracking seen bases in *counter*.

    The first time a base ID is seen it is returned unchanged; each subsequent
    collision gets an incrementing numeric suffix (``base``, ``base_1``,
    ``base_2``, …). *counter* is mutated in place.

    Args:
        counter: Mapping of base ID to the number of times it has been reused.
        base: The desired base identifier.

    Returns:
        A unique identifier derived from *base*.
    """
    if base in counter:
        counter[base] += 1
        return f"{base}_{counter[base]}"
    counter[base] = 0
    return base


@dataclass(frozen=True)
class MappingRule:
    """A syntactically-parsed COMP_MAPPING row.

    Every field is always present, so consumers never have to guard for a
    key that only some rule types populate.

    Attributes:
        mapping_rule: One of ``"skip"``, ``"fixed"``, ``"implicit"``,
            ``"representation"``, ``"multi_representation"``.
        source_id: Normalized SOURCE (may be empty for a fixed rule).
        target_id: Normalized TARGET (empty only when ``mapping_rule`` is
            ``"skip"``).
        fixed_value: The literal value for a ``"fixed"`` rule, else ``None``.
        source_cl: Codelist URN for the source component, or ``None``.
        target_cl: Codelist URN for the target component, or ``None``.
        default_value: Catch-all target for unlisted source values, or
            ``None``. Only ``representation``/``multi_representation`` rules
            ever set it, but the field exists on every rule.
    """

    mapping_rule: str
    source_id: str
    target_id: str
    fixed_value: str | None = None
    source_cl: str | None = None
    target_cl: str | None = None
    default_value: str | None = None


@typechecked
def _extract_mapping_rule(row: "pd.Series") -> MappingRule:
    """Parse a COMP_MAPPING row into a :class:`MappingRule`.

    This performs *syntax-level* validation only; it never touches external
    data.

    Args:
        row: A COMP_MAPPING row with (at least) ``SOURCE``, ``TARGET`` and
            ``MAPPING_RULES`` entries, plus optional ``SOURCE_CL``,
            ``TARGET_CL`` and ``DEFAULT_VALUE``.

    Returns:
        A :class:`MappingRule` with every field populated.

    Raises:
        ValueError: If the rule is syntactically invalid (e.g. a bad ``fixed:``
            format), if ``SOURCE`` is missing for an implicit/representation
            rule, or for unknown rule strings.
    """
    source_id = _cell_str(row, "SOURCE")
    target_id = _cell_str(row, "TARGET")
    raw_rule = str(row.get("MAPPING_RULES", "")).strip()

    # Extract optional codelist URNs (None when absent or empty)
    raw_source_cl = row.get("SOURCE_CL")
    source_cl = str(raw_source_cl).strip() if pd.notna(raw_source_cl) else ""
    source_cl = source_cl or None
    raw_target_cl = row.get("TARGET_CL")
    target_cl = str(raw_target_cl).strip() if pd.notna(raw_target_cl) else ""
    target_cl = target_cl or None

    # Optional default (catch-all) target value (None when absent or empty)
    raw_default = row.get("DEFAULT_VALUE")
    default_value = str(raw_default).strip() if pd.notna(raw_default) else ""
    default_value = default_value or None

    # Skip when TARGET is empty or rule is missing-ish
    if not target_id or _is_missing_token(raw_rule):
        return MappingRule(
            mapping_rule="skip",
            source_id=source_id,
            target_id=target_id,
            source_cl=source_cl,
            target_cl=target_cl,
        )

    rule_lower = raw_rule.lower()

    # fixed:<VALUE>
    if rule_lower.startswith("fixed:"):
        parts = raw_rule.split(":", 1)
        if len(parts) < 2 or not parts[1].strip():
            raise ValueError(f"Invalid fixed rule format: {raw_rule}")
        fixed_val = parts[1].strip()
        return MappingRule(
            mapping_rule="fixed",
            source_id=source_id,
            target_id=target_id,
            fixed_value=fixed_val,
            source_cl=source_cl,
            target_cl=target_cl,
        )

    # implicit
    if rule_lower == "implicit":
        if not source_id:
            raise ValueError(
                "Implicit map rule requires a non-empty 'SOURCE' component ID."
            )
        return MappingRule(
            mapping_rule="implicit",
            source_id=source_id,
            target_id=target_id,
            source_cl=source_cl,
            target_cl=target_cl,
        )

    # representation
    if rule_lower == "representation":
        if not source_id or not target_id:
            raise ValueError(
                "Representation map rule requires non-empty 'SOURCE' and "
                "'TARGET' component ID."
            )
        return MappingRule(
            mapping_rule="representation",
            source_id=source_id,
            target_id=target_id,
            source_cl=source_cl,
            target_cl=target_cl,
            default_value=default_value,
        )

    # multi_representation: SOURCE is a '|'-delimited list of >= 2 components
    if rule_lower == "multi_representation":
        source_tokens = [s.strip() for s in source_id.split("|") if s.strip()]
        if len(source_tokens) < 2:
            raise ValueError(
                "Multi-representation map rule requires at least two source "
                "components joined by '|' (e.g. 'FREQ|REF_AREA'). Use "
                "'representation' for a single source component."
            )
        return MappingRule(
            mapping_rule="multi_representation",
            source_id=source_id,
            target_id=target_id,
            source_cl=source_cl,
            target_cl=target_cl,
            default_value=default_value,
        )

    # unknown
    raise ValueError(f"Unknown mapping rule: '{raw_rule}'")


@typechecked
def _extract_representation_map(
    rep_data: dict[str, pd.DataFrame],
    source_id: str,
    target_id: str,
    rep_data_error: str | None = None,
) -> pd.DataFrame:
    """Build the (source, target) mapping pairs DataFrame for a representation rule.

    Resolves column names and performs sanitization.

    Args:
        rep_data: Dictionary containing 'source' and 'target' DataFrames
            derived from REP_MAPPING.
        source_id: Component identifier to be matched to a column in
            ``rep_data['source']``.
        target_id: Component identifier to be matched to a column in
            ``rep_data['target']``.
        rep_data_error: Optional message from an earlier REP_MAPPING parse
            failure, appended to the raised error when ``rep_data`` is empty.

    Returns:
        Two-column DataFrame with columns ['source', 'target'], NA rows
        dropped and duplicate row pairs removed.

    Raises:
        ValueError: If rep_data is missing, either DataFrame is empty,
            column resolution fails, or no valid mapping pairs remain.
    """
    # 1) Validate presence and non-empty REP_MAPPING inputs
    if (
        not rep_data
        or "source" not in rep_data
        or "target" not in rep_data
        or rep_data["source"] is None
        or rep_data["target"] is None
        or rep_data["source"].empty
        or rep_data["target"].empty
    ):
        message = (
            "Mapping rule requires 'REP_MAPPING' sheet with data, but it was "
            "invalid or empty."
        )
        if rep_data_error:
            message += f" Underlying REP_MAPPING error: {rep_data_error}"
        raise ValueError(message)

    source_df = rep_data["source"]
    target_df = rep_data["target"]

    # 2) Resolve actual column names (can raise if not found)
    actual_source_col = _match_column_name(source_id, source_df.columns.tolist())
    actual_target_col = _match_column_name(target_id, target_df.columns.tolist())

    # 3) Build, sanitize, and deduplicate pairs
    rep_mapping_df = (
        pd.DataFrame(
            {
                "source": source_df[actual_source_col],
                "target": target_df[actual_target_col],
            }
        )
        .dropna(subset=["source", "target"], how="any")
        .drop_duplicates()
    )

    # 4) Enforce non-empty result
    if rep_mapping_df.empty:
        raise ValueError(
            f"No valid mapping rows found between source column '{actual_source_col}' "
            f"and target column '{actual_target_col}'."
        )

    return rep_mapping_df


@typechecked
def _extract_multi_representation_map(
    rep_data: dict[str, pd.DataFrame],
    source_ids: list[str],
    target_id: str,
    rep_data_error: str | None = None,
) -> pd.DataFrame:
    """Build the value-tuple mapping DataFrame for a multi-representation rule.

    Resolves each source component ID and the target component ID to columns in
    the parsed REP_MAPPING data, then assembles a DataFrame whose columns are
    named after the component IDs (so they line up with the ``source_cols`` /
    ``target_cols`` consumed by :func:`build_multi_component_map`).

    Args:
        rep_data: Dictionary containing 'source' and 'target' DataFrames
            derived from REP_MAPPING.
        source_ids: Ordered source component IDs, each matched to a column in
            ``rep_data['source']``.
        target_id: Target component ID, matched to a column in
            ``rep_data['target']``.
        rep_data_error: Optional message from an earlier REP_MAPPING parse
            failure, appended to the raised error when ``rep_data`` is empty.

    Returns:
        A DataFrame with one column per ``source_ids`` entry followed by a
        ``target_id`` column, NA rows dropped and duplicate tuples removed.

    Raises:
        ValueError: If rep_data is missing/empty, a column cannot be resolved,
            or no valid mapping rows remain.
    """
    # 1) Validate presence and non-empty REP_MAPPING inputs
    if (
        not rep_data
        or "source" not in rep_data
        or "target" not in rep_data
        or rep_data["source"] is None
        or rep_data["target"] is None
        or rep_data["source"].empty
        or rep_data["target"].empty
    ):
        message = (
            "Mapping rule requires 'REP_MAPPING' sheet with data, "
            "but it was invalid or empty."
        )
        if rep_data_error:
            message += f" Underlying REP_MAPPING error: {rep_data_error}"
        raise ValueError(message)

    source_df = rep_data["source"]
    target_df = rep_data["target"]

    # 2) Resolve actual column names (can raise if not found), keyed by component ID
    columns: dict[str, pd.Series] = {}
    for source_id in source_ids:
        actual_col = _match_column_name(source_id, source_df.columns.tolist())
        columns[source_id] = source_df[actual_col]
    actual_target_col = _match_column_name(target_id, target_df.columns.tolist())
    columns[target_id] = target_df[actual_target_col]

    # 3) Build, sanitize, and deduplicate tuples
    rep_mapping_df = pd.DataFrame(columns).dropna(how="any").drop_duplicates()

    # 4) Enforce non-empty result
    if rep_mapping_df.empty:
        raise ValueError(
            f"No valid mapping rows found for sources {source_ids} "
            f"and target '{target_id}'."
        )

    return rep_mapping_df
